#!/usr/bin/env sh

# Binary space layout
# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# Window placement for new windows added to the screen and how they are split
yabai -m config window_placement second_child

# mouse settings
yabai -m config mouse_follows_focus on

# mouse modifier
yabai -m config mouse_modifier alt
# drag + left click to move window
yabai -m config mouse_action1 move
# drag + right click to resize window
yabai -m config mouse_action2 resize
# swap window when dragged to the center of another window
yabai -m config mouse_drop_action1 swap

# disable some applications from being managed by yabai
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Shottr$" manage=off
yabai -m rule --add app="System Information" manage=off
yabai -m rule --add app="Norton 360" manage=off

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
yabai -m config external_bar all:0:29
